from pathwaygat.utils import *
from pathwaygat.model import PathwayGAT
import pandas as pd
import torch
from torch_geometric.loader import DataLoader
from sklearn.metrics import accuracy_score
import pickle

pathway_file = '../data/wikipath2021.tsv'
microbe_file = '../data/TCGA_COAD.microbe.txt'
gene_file = '../data/TCGA_COAD.gene.txt'
microbe_gene_file = '../data/TCGA_COAD.gene_microbe_association.txt'
meta_file = '../data/COAD_sample_metadata.processed.txt'
class_name = 'sample_type2'
output_prefix = ''
batch_size = 32
hidden_channels = 128
learning_rate = 0.001
epochs = 35
sample_num = 0
seed = 42

torch.manual_seed(seed)
random.seed(seed)
np.random.seed(seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

wpgene, wpdict = parse_pathway_file(pathway_file)
wpadj = calculate_adjacency(wpdict)
wp_edge = adjacency_to_edge_index(wpadj)

microbe_gene_corr = read_microbe_gene_corr(microbe_gene_file, 2)
microbe_abundance = pd.read_csv(microbe_file, header=0, delimiter='\t', index_col=0)

# Added by Weihao to downsample 
if sample_num > 0:
    sample_list = random.sample(range(microbe_abundance.shape[0]), sample_num)
else:
    sample_list = range(microbe_abundance.shape[0])
with open(f'{output_prefix}_sample_index.pkl', 'wb') as f:
    pickle.dump(sample_list, f)
microbe_abundance = microbe_abundance.iloc[sample_list, ]

# Define all cutoffs to analyze
cutoffs = [0.09, 0.1, 0.12, 0.14, 0.15, 0.17, 0.23]

microbe_gene_corr_columns_set = set(microbe_gene_corr.columns)

# Store results for all cutoffs
all_pathway_microbe_tables = {}  # pathway-microbe boolean tables
all_microbe_pathway_counts = {}  # number of pathways per microbe
all_pathway_microbe_counts = {}  # number of microbes per pathway

for cutoff in cutoffs:
    pathway_microbe_mask = {}
    
    for pathway, genes in wpdict.items():
        overlapping_genes = list(set(genes) & microbe_gene_corr_columns_set)
        if not overlapping_genes:
            continue
        
        filtered_corr = microbe_gene_corr[overlapping_genes].dropna(how='all')
        mask = (filtered_corr.abs() > cutoff).any(axis=1)
        pathway_microbe_mask[pathway] = mask
    
    # Create pathway-microbe table
    pathway_microbe_table = pd.DataFrame(pathway_microbe_mask).T
    pathway_microbe_table = pathway_microbe_table.fillna(False)
    all_pathway_microbe_tables[cutoff] = pathway_microbe_table
    
    # Count pathways per microbe (column sum)
    microbe_pathway_count = pathway_microbe_table.sum(axis=0)
    all_microbe_pathway_counts[cutoff] = microbe_pathway_count
    
    # Count microbes per pathway (row sum)
    pathway_microbe_count = pathway_microbe_table.sum(axis=1)
    all_pathway_microbe_counts[cutoff] = pathway_microbe_count
    
    print(f"Cutoff {cutoff}: {len(pathway_microbe_table)} pathways, {len(pathway_microbe_table.columns)} microbes")

print("\nDone processing all cutoffs.")

# Create summary table: number of pathways for each microbe across cutoffs
# Rows = microbes, Columns = cutoffs
microbe_pathway_summary = pd.DataFrame(all_microbe_pathway_counts)
microbe_pathway_summary.columns = [f'cutoff_{c}' for c in microbe_pathway_summary.columns]
microbe_pathway_summary = microbe_pathway_summary.sort_values(by='cutoff_0.15', ascending=False)

print("Number of pathways per microbe across cutoffs:")
print(f"Shape: {microbe_pathway_summary.shape}")

# Save the summary tables
output_dir = '../result/'
microbe_pathway_summary.to_csv(f'{output_dir}microbe_pathway_count_by_cutoff.csv')
print(f"Saved: {output_dir}microbe_pathway_count_by_cutoff.csv")

import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.manifold import TSNE

# File paths (same as final_graph_microbe_cutoff.ipynb)
result_dir = '../result/'

# Read microbe abundance data (samples x microbes)
microbe_abundance = pd.read_csv(microbe_file, header=0, delimiter='\t', index_col=0)
print(f"Microbe abundance shape: {microbe_abundance.shape}")
print(f"Samples: {microbe_abundance.shape[0]}, Microbes: {microbe_abundance.shape[1]}")

# Read the microbe pathway counts summary (generated by final_graph_microbe_cutoff.ipynb)
microbe_pathway_counts = pd.read_csv(f'{result_dir}microbe_pathway_count_by_cutoff.csv', index_col=0)
print(f"Microbe pathway counts shape: {microbe_pathway_counts.shape}")
microbe_pathway_counts.head()

# Transpose to get microbes as rows (for PCA on microbes)
microbe_data_T = microbe_abundance.T
print(f"Transposed shape (microbes x samples): {microbe_data_T.shape}")

# Standardize the data
scaler = StandardScaler()
microbe_scaled = scaler.fit_transform(microbe_data_T)

# Perform t-SNE on standardized microbe data
tsne = TSNE(n_components=2, random_state=42, perplexity=min(30, len(microbe_scaled)-1))
tsne_result = tsne.fit_transform(microbe_scaled)

# Create DataFrame with t-SNE results
tsne_df = pd.DataFrame({
    'Microbe': microbe_data_T.index,
    'tSNE1': tsne_result[:, 0],
    'tSNE2': tsne_result[:, 1]
})
tsne_df = tsne_df.set_index('Microbe')

# Merge with pathway counts
tsne_merged = tsne_df.loc[common_microbes].copy()
tsne_merged['pathways_0.15'] = microbe_pathway_counts.loc[common_microbes, 'cutoff_0.15']
tsne_merged['pathways_0.23'] = microbe_pathway_counts.loc[common_microbes, 'cutoff_0.23']

print(f"t-SNE completed. Merged data shape: {tsne_merged.shape}")
tsne_merged.head()

# Plot t-SNE colored by number of pathways
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Plot 1: Cutoff 0.15
scatter1 = axes[0].scatter(
    tsne_merged['tSNE1'], 
    tsne_merged['tSNE2'], 
    c=tsne_merged['pathways_0.15'], 
    cmap='viridis', 
    alpha=0.7,
    s=50
)
axes[0].set_xlabel('t-SNE 1')
axes[0].set_ylabel('t-SNE 2')
axes[0].set_title('t-SNE of Microbes\n(Colored by # Pathways at Cutoff 0.15)')
cbar1 = plt.colorbar(scatter1, ax=axes[0])
cbar1.set_label('Number of Pathways')

# Plot 2: Cutoff 0.23
scatter2 = axes[1].scatter(
    tsne_merged['tSNE1'], 
    tsne_merged['tSNE2'], 
    c=tsne_merged['pathways_0.23'], 
    cmap='viridis', 
    alpha=0.7,
    s=50
)
axes[1].set_xlabel('t-SNE 1')
axes[1].set_ylabel('t-SNE 2')
axes[1].set_title('t-SNE of Microbes\n(Colored by # Pathways at Cutoff 0.23)')
cbar2 = plt.colorbar(scatter2, ax=axes[1])
cbar2.set_label('Number of Pathways')

plt.tight_layout()
plt.savefig(f'{result_dir}tsne_microbes_by_pathway_count.pdf', dpi=300, bbox_inches='tight')
plt.show()

print(f"Saved: {result_dir}tsne_microbes_by_pathway_count.pdf")